const works = [
  {
    "name": "김시우",
    "studentId": "20251164",
    "folder": "kim-siwoo-sumsum",
    "title": "숨숨",
    "sense": "함께 있지만 혼자 있는 것만 같은 순간",
    "description": "함께 있으면서도 혼자 있는 것만 같은 순간, 우리는 내면을 들여다보고 스스로를 돌볼 수 있습니다. 숨 가쁜 현실과 대비되는 자신만의 속도로 일상을 지켜나가는 Creature의 모습은 이를 대변합니다. Creature를 관찰하고 마우스 클릭으로 그 일상에 간접적으로 다가가는 경험을 통해, 우리는 위안과 나 자신을 돌보고자 하는 마음을 갖게 됩니다.",
    "link": "https://editor.p5js.org/us157202/full/ugjGrkj89",
    "localLink": "works/kim-siwoo-sumsum/index.html",
    "displayMode": "embed",
    "thumbnail": "thumbnails/s20251164.jpg",
    "inputDevice": "마우스 입력",
    "inputAction": "클릭",
    "output": "사운드 출력",
    "interactionGuide": "화면을 마우스로 클릭해보세요.",
    "reaction": "캐릭터가 반응하고 행동합니다",
    "outputGuide": "사운드 있음",
    "sound": true,
    "rawInput": "#마우스클릭 #사운드",
    "rawOutput": "사운드 있음",
    "p5Original": "https://editor.p5js.org/us157202/full/ugjGrkj89",
    "thumbnailOriginal": "https://drive.google.com/open?id=1aBPQDJtuyaXTn8gptOEVENW1CnZEKXKL",
    "cropTop": 56
  },
  {
    "name": "오성연",
    "studentId": "20253217",
    "folder": "oh-seongyeon-rainforest",
    "title": "비 내리는 숲의 조각 속으로",
    "sense": "비 오는 여름, 녹빛이 우거진 가로수길을 산책하며 느낀 포근하고 축축한 공기와 시각적 즐거움",
    "description": "이 작품은 비 내리는 신비로운 숲의 풍경과 그 속을 유영하는 생명체들의 움직임을 시각화한 인터랙티브 미디어 아트입니다. 마우스의 움직임을 부드럽게 추적하는 요정은 관람자의 가상 아바타가 되어 화면 속 자연환경과 끊임없이 상호작용합니다. 화면을 클릭할 때마다 실시간으로 변하는 날씨는 빛내림 효과와 창문에 맺히는 물방울, 현실적인 번개 연출을 통해 몽환적이면서도 깊이감 있는 몰입감을 선사합니다. 군집 알고리즘을 기반으로 구현된 새, 나비, 반딧불이 등의 생명체들은 요정과의 거리에 따라 반응하며 빛 파티클을 남기고 생동감 넘치게 화면을 가득 채웁니다. 이 작품은 자연의 고요함과 생명력을 유기적으로 연결하여, 관람객에게 환상 동화 속에 들어온 듯한 영롱하고 입체적인 시각 경험을 제공합니다.",
    "link": "https://editor.p5js.org/osy1027a/full/G18ncUOj8",
    "localLink": "works/oh-seongyeon-rainforest/index.html",
    "displayMode": "embed",
    "thumbnail": "thumbnails/s20253217.jpg",
    "inputDevice": "마우스 입력",
    "inputAction": "클릭·움직임",
    "output": "",
    "interactionGuide": "마우스를 움직여 생명체들을 쫓아보세요. · 화면을 클릭해 날씨를 바꿔보세요.",
    "reaction": "곤충들이 마우스를 피해 움직이지만 결국 닿았을 때 빛 파티클을 뿌리게 됩니다.",
    "outputGuide": "",
    "sound": false,
    "rawInput": "#마우스이동 #마우스클릭",
    "rawOutput": "",
    "p5Original": "https://editor.p5js.org/osy1027a/full/G18ncUOj8",
    "thumbnailOriginal": "https://drive.google.com/open?id=1UuZ7geRHbsG44pQnKrk7hAPTx_xgV-CY",
    "cropTop": 72
  },
  {
    "name": "정혜윤",
    "studentId": "20253373",
    "folder": "jung-hyeyoon-pulse-bloom",
    "title": "Pulse Bloom",
    "sense": "딥 하우스 음악의 둥둥거리는 비트(126 BPM)에 맞춰 심장이 뛰는 감각",
    "description": "Pulse Bloom은 딥 하우스 음악 특유의 둥둥거리는 베이스와 126 BPM 비트에 맞춰 심장이 뛰는 감각에서 출발한 인터랙티브 작품이다. 생명체는 관람자의 접근과 공격에 반응하며 형태를 수축 및 팽창시키고, 감정 상태에 따라 유기적으로 변형된다. 반복되는 베이스 리듬은 Creature의 맥박과 움직임으로 시각화되며, 관람자는 이를 자극하거나 교감하면서 살아있는 존재와 상호작용하는 경험을 하게 된다. 생명체의 붕괴와 재생 과정을 통해 리듬, 생명성, 그리고 관계의 변화를 감각적으로 체험할 수 있다.",
    "link": "works/jung-hyeyoon-pulse-bloom/index.html",
    "localLink": "works/jung-hyeyoon-pulse-bloom/index.html",
    "displayMode": "local",
    "thumbnail": "thumbnails/s20253373.jpeg",
    "inputDevice": "마우스 입력",
    "inputAction": "클릭·움직임",
    "output": "사운드 출력",
    "interactionGuide": "마우스를 생명체 가까이 가져가보세요. · 화면을 클릭해보세요.",
    "reaction": "마우스를 이용해 생명체에 가까이 다가갈 시 생명체는 더욱 활발하게 맥동하며 그 형태가 왜곡됩니다. 화면의 아무 곳을 마우스로 클릭하면 하단에서 레이저가 발사됩니다. 이때 생명체는 공격을 받으면 순간적으로 수축하고 크기가 감소하며, 세 번의 공격을 받으면 폭발과 함께 붕괴됩니다. 또한 빗맞췄을 시에는 레이저로부터 회피하는 행동을 보입니다. 이후 생명체는 일정 시간이 지난 뒤 다시 생성됩니다.",
    "outputGuide": "사운드 있음",
    "sound": true,
    "rawInput": "#마우스이동 #마우스클릭 #사운드",
    "rawOutput": "사운드 있음",
    "p5Original": "https://editor.p5js.org/xoderline/full/PstTIQgZR",
    "thumbnailOriginal": "https://drive.google.com/open?id=1bjA9mRY2Rhsc9Qrlm2Q0WqTecThakr2j"
  },
  {
    "name": "정유민",
    "studentId": "20251188",
    "folder": "jung-yumin-in-sense",
    "title": "IN-SENSE",
    "sense": "지친 날 방 안에서 인센스 연기를 바라보며 느꼈던 차분하고 신비로운 감각",
    "description": "바쁜 하루를 보내고 난 밤, 인센스를 피우며 연기를 가만히 바라보는 것은 마음을 안정시켜 준다. 때로는 연기가 살아 움직이는 존재 같다. 작품 속 Creature는 당신을 현실에서 벗어나 편안한 공간으로 유도하는 신비로운 존재이다. 가만히 응시하며 Creature들이 화면을 채우는 모습을 바라보자. 마우스를 클릭하여 당신의 존재를 알리면 원을 그리며 반기다가도, 마우스의 움직임에 따라 흐트러지는 오묘한 성격도 느껴보길 바란다.",
    "link": "works/jung-yumin-in-sense/index.html",
    "localLink": "works/jung-yumin-in-sense/index.html",
    "displayMode": "local",
    "thumbnail": "thumbnails/s20251188.jpg",
    "inputDevice": "마우스 입력",
    "inputAction": "클릭·움직임",
    "output": "",
    "interactionGuide": "마우스를 천천히 움직이거나 화면을 클릭해보세요.",
    "reaction": "마우스의 움직임에 따라 크리쳐가 밀려나고, 클릭한 위치로 크리쳐들이 원을그리며 모여듭니다.",
    "outputGuide": "",
    "sound": false,
    "rawInput": "#마우스이동 #마우스클릭",
    "rawOutput": "",
    "p5Original": "https://editor.p5js.org/chickencheek/full/P5chuAt7y",
    "thumbnailOriginal": "https://drive.google.com/open?id=1in536t2WeQQDF5p8Ei2NmCiWwyhAIcuE"
  },
  {
    "name": "이다해",
    "studentId": "20268009",
    "folder": "lee-dahae-haebangchon",
    "title": "해방촌의 하루",
    "sense": "해방촌에서 느꼈던 하루의 흐름과 살아있다는 느낌",
    "description": "해방촌은 나에게 하나의 살아있는 생명체처럼 느껴졌다. 이 작품은 시간의 흐름에 따라 변화하는 해방촌의 풍경과 생동감을 담고 있다. 건물, 전선, 그리고 작은 움직임들을 통해 해방촌의 하루를 표현하였다.",
    "link": "works/lee-dahae-haebangchon/index.html",
    "localLink": "works/lee-dahae-haebangchon/index.html",
    "displayMode": "local",
    "thumbnail": "thumbnails/s20268009.jpg",
    "inputDevice": "마우스 입력",
    "inputAction": "움직임",
    "output": "",
    "interactionGuide": "마우스를 천천히 움직여보세요.",
    "reaction": "용자는 마우스를 움직이며 해방촌의 분위기와 변화를 경험할 수 있다.",
    "outputGuide": "",
    "sound": false,
    "rawInput": "#마우스이동",
    "rawOutput": "",
    "p5Original": "https://editor.p5js.org/ldh20422/full/G-AUmdLGq",
    "thumbnailOriginal": "https://drive.google.com/open?id=1_1p_R2Giz-IKf2yvPXAiFv_CrHJdInIj"
  },
  {
    "name": "이예림",
    "studentId": "20253286",
    "folder": "lee-yerim-duck",
    "title": "빛과 오리의 숨바꼭질(Hide-and-Seek Between Light and a Duck)",
    "sense": "아침 셔틀버스에서 강가의 오리를 찾으며 느꼈던 두근거림과 기쁨, 실망",
    "description": "매일 아침 버스를 타고 강가를 지나며 오리를 찾던 나의 일상적인 루틴과 그 순간의 감정을 크리처로 시각화한 작품입니다. 크리처들은 오리를 발견하면 형형색색의 폭죽을 터뜨리며 기쁨을 표현하고, 오리를 찾지 못하면 물거품처럼 흩어지며 아쉬움을 드러냅니다. 사용자는 크리처들의 조력자가 되어 숨겨진 오리를 찾고, 크리처들과 감정을 공유하며 작은 발견의 기쁨을 경험하게 됩니다.",
    "link": "works/lee-yerim-duck/index.html",
    "localLink": "works/lee-yerim-duck/index.html",
    "displayMode": "local",
    "thumbnail": "thumbnails/s20253286.jpg",
    "inputDevice": "마우스 입력",
    "inputAction": "클릭·움직임",
    "output": "사운드 출력",
    "interactionGuide": "마우스를 움직여 숨겨진 오리를 찾아 클릭해보세요.",
    "reaction": "크리처들은 마우스를 따라 움직이며, 오리의 발견 여부에 따라 서로 다른 색, 형태로 변화합니다.",
    "outputGuide": "사운드 있음",
    "sound": true,
    "rawInput": "#마우스이동 #마우스클릭 #사운드",
    "rawOutput": "사운드 있음",
    "p5Original": "https://editor.p5js.org/eile35/full/aJjNwsiew",
    "thumbnailOriginal": "https://drive.google.com/open?id=1FgQ0ETWz7gmIOqCPpcIkOK0BFjDmPFF6"
  },
  {
    "name": "이하은",
    "studentId": "20252870",
    "folder": "lee-haeun-music-spirit",
    "title": "음악의 정령",
    "sense": "음악을 연주할 때 온몸으로 선율과 리듬을 즐기는 감각",
    "description": "음악을 연주하면 내 안에 그 선율이 울리는 것처럼 즐거운 기분이 듭니다. 이 무대의 자그마한 녀석도 음악을 사랑하고 즐기는 존재입니다. 어서 춤추고 싶어 하는 녀석을 클릭해 공연을 시작하면, 누르는 키에 따라 신나게 춤을 춥니다. 공연을 무사히 끝내면 감사를 표하며 커튼 뒤로 들어가지만, 중간에 공연을 멈추면 화를 내고 사라져버립니다.",
    "link": "works/lee-haeun-music-spirit/index.html",
    "localLink": "works/lee-haeun-music-spirit/index.html",
    "displayMode": "local",
    "thumbnail": "thumbnails/s20252870.png",
    "inputDevice": "마우스·키보드 입력",
    "inputAction": "클릭·키조작",
    "output": "사운드 출력",
    "interactionGuide": "화면을 클릭해 시작하고, 키보드 D·F·J·K 키를 눌러 춤추게 해보세요. · 크리처가 스스로를 가리키면 클릭해보세요.",
    "reaction": "입력한 키에 따라 각각 다른 동작을 하며 춤을 춥니다.",
    "outputGuide": "사운드 있음",
    "sound": true,
    "rawInput": "#마우스클릭 #키보드 #사운드",
    "rawOutput": "사운드 있음",
    "p5Original": "https://editor.p5js.org/herien718/full/ygWtgWgRd",
    "thumbnailOriginal": "https://drive.google.com/open?id=1YPwU1HG4zE_N9WvBr--OSHvqwqLvYYQo"
  },
  {
    "name": "임윤채",
    "studentId": "20253330",
    "folder": "lim-yoonchae-resonance",
    "title": "공명(Resonance)",
    "sense": "음악 공연에서 처음 만난 낯선 사람들과 함께 같은 음악을 듣고 즐기던 순간의 감각",
    "description": "서로 모르는 사람들이 하나의 음악을 들으며 같은 감정을 공유하던 순간, 그 '공명'의 감각에서 시작되었습니다. 화면을 클릭하여 사운드를 재생하면, 당신과 공명하는 친화적인 Creature들이 음악에 맞춰 스며들기 시작합니다. 마우스를 움직이거나 드래그하는 손짓을 통해 Creature들과 마음을 나눌 수 있으며, 당신의 움직임 속도와 리듬에 따라 이들의 빛과 크기, 군집의 흐름이 다채롭게 변화합니다. 때로는 키보드 방향키로 파동을 일으키거나 진정시키며 교감을 나눌 수도 있습니다. 음악과 시각적 파형이 하나로 어우러지는 이 공간에서, Creature들과 손짓을 맞춰보며 따뜻한 연결과 스며듦의 순간을 경험해 보세요.",
    "link": "works/lim-yoonchae-resonance/index.html",
    "localLink": "works/lim-yoonchae-resonance/index.html",
    "displayMode": "local",
    "thumbnail": "thumbnails/s20253330.png",
    "inputDevice": "마우스·키보드 입력",
    "inputAction": "클릭·움직임·키조작",
    "output": "사운드 출력",
    "interactionGuide": "화면을 클릭해 시작하고, 마우스를 자유롭게 움직여보세요. · 키보드 위아래 방향키도 눌러보세요.",
    "reaction": "키보드 방향키의 위아래, 마우스를 드래그하는 움직임 속도와 리듬에 따라 이들의 빛과 크기, 군집의 흐름이 다채롭게 변화합니다. 클릭함에 따라 파동이 일어나고 creature가 빛납니다.",
    "outputGuide": "사운드 있음",
    "sound": true,
    "rawInput": "#마우스이동 #마우스클릭 #키보드 #사운드",
    "rawOutput": "사운드 있음",
    "p5Original": "https://editor.p5js.org/253330/full/p6b2-JkIE",
    "thumbnailOriginal": "https://drive.google.com/open?id=1P_uw3HkjHS2-35E7F-X755s7Ey0lPz6p"
  },
  {
    "name": "김윤아",
    "studentId": "20251166",
    "folder": "kim-yuna-bingle",
    "title": "빙글둠칫",
    "sense": "모두가 각자의 삶을 살아가는 도시 속에서, 나 홀로 음악을 들으며 신나게 걸어가는 감각",
    "description": "음악을 듣기 전에는 애벌레가 무표정으로 빠르게 공간을 유영한다. 주변의 다른 점들을 무시하고 홀로 움직이고 있다. 그러나 사용자가 재생 버튼을 누르면 애벌레가 좋아하는 노래가 재생된다. 음악이 재생되면 애벌레는 웃음을 지으며 음원이 나오는 LP에 붙어서 도시를 누빈다. 흥이 오른 애벌레 주위에 긍정적인 기운이 퍼져 나오고, 애벌레를 클릭하면 비트에 맞춰 고개를 까닥까닥거린다.",
    "link": "works/kim-yuna-bingle/index.html",
    "localLink": "works/kim-yuna-bingle/index.html",
    "displayMode": "local",
    "thumbnail": "thumbnails/s20251166.png",
    "inputDevice": "마우스 입력",
    "inputAction": "클릭",
    "output": "사운드 출력",
    "interactionGuide": "화면 속 LP판을 클릭해보세요.",
    "reaction": "마우스 클릭에 따라 음악이 재생되거나 애벌레의 움직임이 달라집니다.",
    "outputGuide": "사운드 있음",
    "sound": true,
    "rawInput": "#마우스클릭 #사운드",
    "rawOutput": "사운드 있음",
    "p5Original": "https://editor.p5js.org/yunakimyuna/full/pvjP7_8zr",
    "thumbnailOriginal": "https://drive.google.com/open?id=1D8Io3IdLtdB6h6AnOIcSs0TlM-W_E5E_"
  },
  {
    "name": "안정원",
    "studentId": "20252803",
    "folder": "ahn-jungwon-echo",
    "title": "꿈 속의 메아리",
    "sense": "하굣길에 좋아하는 음악을 들으며 버스 창밖의 풍경을 바라본 감각",
    "description": "이 작품은 음악에 몰입하여 듣고, 그 음악에 직접 참여해볼 수 있는 작품이다. 음악을 통해 풍경이 어떻게 달라질 수 있는지도 상상해볼 수 있다. 이 음악을 들으며 느꼈던 감각을 그대로 전달하고 싶었다.",
    "link": "works/ahn-jungwon-echo/index.html",
    "localLink": "works/ahn-jungwon-echo/index.html",
    "displayMode": "local",
    "thumbnail": "thumbnails/s20252803.png",
    "inputDevice": "키보드·기타 입력",
    "inputAction": "키조작·연주",
    "output": "사운드 출력",
    "interactionGuide": "앞에 놓인 기타를 음악에 맞춰 연주해보세요. · 키보드 Q(기타)·W(베이스)·E(드럼)·R(보컬)로 악기를 하나씩 꺼보세요.",
    "reaction": "기타를 치면 배경이 왜곡되고 크리쳐가 반응한다. 그리고 q,w,e,r을 각각 누르거나 한번에 누르면 각 키에 해당하는 악기들이 음소거되며 환경이 변화한다.",
    "outputGuide": "사운드 있음, 오디오 인터페이스를 통하여 입력, 출력 되어야 합니다.",
    "sound": true,
    "rawInput": "#키보드 #기타연주 #사운드",
    "rawOutput": "사운드 있음, 오디오 인터페이스를 통하여 입력, 출력 되어야 합니다.",
    "p5Original": "https://editor.p5js.org/a88446399/full/0xq_UTRuY",
    "thumbnailOriginal": "https://drive.google.com/open?id=1Hj2m6JO12dQ_SFFYoSivo3-e4RKpAWM0"
  },
  {
    "name": "허찬우",
    "studentId": "20231601",
    "folder": "heo-chanwoo-yudae",
    "title": "유대",
    "sense": "낯선 것에 다가갔을 때 열리는 새로운 세계",
    "description": "새로운 사람, 존재, 상대에 대해 알아갔을 때 마치 새로운 세상에 발을 들이는 듯한 느낌입니다. 이 작품 속 Creature는 소심하고 불안이 많은 존재이며 웹캠을 통해 세상을 바라봅니다. Creature가 움직임을 감지하면 경계 태세를 갖추며 동요하지만, 어떠한 움직임도 감지되지 않으면 안정된 상태가 되면서 자신만의 평온한 세계를 보여줍니다. 당신이 안정된 상태를 좋아하는 Creature를 존중해준다면, Creature는 당신에게 친밀감을 느끼고 새로운 세계를 보여줄 것입니다.",
    "link": "works/heo-chanwoo-yudae/index.html",
    "localLink": "works/heo-chanwoo-yudae/index.html",
    "displayMode": "local",
    "thumbnail": "thumbnails/s20231601.jpeg",
    "inputDevice": "웹캠 입력",
    "inputAction": "움직임",
    "output": "",
    "interactionGuide": "웹캠 앞에서 천천히 움직여보세요.",
    "reaction": "웹캠이 움직임을 감지하면 입자와 배경이 불안정한 상태를 보입니다.",
    "outputGuide": "",
    "sound": false,
    "rawInput": "#웹캠 #움직임감지",
    "rawOutput": "",
    "p5Original": "https://editor.p5js.org/matthur/full/XGQucFT35",
    "thumbnailOriginal": "https://drive.google.com/open?id=1bQaLSjsIPa0Cfta058jBtrL73dKHXVHA"
  },
  {
    "name": "강다은",
    "studentId": "20251159",
    "folder": "kang-daeun-frost",
    "title": "서리 내린 숲",
    "sense": "겨울 새벽, 고요한 숲을 산책할 때의 감각",
    "description": "겨울 아침, 고요한 숲을 거닐 때 느껴지는 시리고도 몽글몽글한 순간에서 시작했습니다. 이 작품 속 Creature는 고요한 숲속에서 자기들끼리 조용히 살아가는 존재입니다. 관람자가 가만히 있으면 서서히 다가와 그들을 관찰하며 속닥이지만, 큰 움직임을 보이면 놀라 달아납니다. 호기심이 많고 장난스럽지만, 아주 소심한 성격의 존재들입니다.",
    "link": "works/kang-daeun-frost/index.html",
    "localLink": "works/kang-daeun-frost/index.html",
    "displayMode": "local",
    "thumbnail": "thumbnails/s20251159.jpg",
    "inputDevice": "웹캠 입력",
    "inputAction": "클릭·움직임",
    "output": "사운드 출력",
    "interactionGuide": "웹캠 앞에 가만히 서 있어보세요. · 몸을 움직이거나 손을 흔들어보세요.",
    "reaction": "가만히 있을 때는 가까이 다가오고 (크기가 커지고), 움직일 때는 달아난다.(속도가 빨라지며 작아진다)",
    "outputGuide": "사운드 있음, 사운드 재생을 위해서는 화면을 한 번 클릭 해야하고, 헤드셋 착용이 필요합니다.",
    "sound": true,
    "rawInput": "#웹캠 #움직임감지 #사운드",
    "rawOutput": "사운드 있음, 사운드 재생을 위해서는 화면을 한 번 클릭 해야하고, 헤드셋 착용이 필요합니다.",
    "p5Original": "https://editor.p5js.org/daeunkang/full/UJQ3iwrCc",
    "thumbnailOriginal": "https://drive.google.com/open?id=1k3psuYp51m3DDZpFSaQxQFDYNaxnopvQ"
  },
  {
    "name": "성수연",
    "studentId": "20252787",
    "folder": "sung-suyeon-breath",
    "title": "숨결 더듬기",
    "sense": "나이 많은 반려견이 잠들어 있을 때, 가만히 배에 손을 대고 호흡을 느끼며 살아있음을 확인하던 순간의 안도감",
    "description": "나이 많은 반려견의 배에 손을 올리고 숨결을 확인하며 느끼는 안도감, 그리고 그 이면의 유한한 생명에 대한 불안감에서 작업을 시작했습니다. 이 Creature는 호흡과 화이트 노이즈로 간당간당한 생명력을 유지하고 있는 위태로운 존재입니다. 사용자가 화면 위에서 마우스를 움직여 빛을 밝히면, 살아있음을 확인하려는 손길에 반응하듯 마찰음과 함께 픽셀이 움직이고 정렬됩니다. 이로써 사용자는 화면을 더듬는 자신의 손길을 통해 안도감과 공포라는 양가적인 감정을 동시에 마주하게 됩니다.",
    "link": "works/sung-suyeon-breath/index.html",
    "localLink": "works/sung-suyeon-breath/index.html",
    "displayMode": "local",
    "thumbnail": "thumbnails/s20252787.png",
    "inputDevice": "마우스 입력",
    "inputAction": "움직임",
    "output": "사운드 출력",
    "interactionGuide": "마우스를 화면 위에서 천천히 움직여보세요.",
    "reaction": "마우스의 위치에 따라 희미한 노란 빛이 밝혀지고, 노이즈 사운드와 함께 글리치가 발생합니다.",
    "outputGuide": "사운드 있음",
    "sound": true,
    "rawInput": "#마우스이동 #사운드",
    "rawOutput": "사운드 있음",
    "p5Original": "https://editor.p5js.org/elly2015/full/MOnxYt4lA",
    "thumbnailOriginal": "https://drive.google.com/open?id=1e3C_PwqfxXhDrLvhnOOgKNqejObsZMuT"
  },
  {
    "name": "나이린아웅",
    "studentId": "20251168",
    "folder": "naylinaung-lights-breathe",
    "title": "When Lights Breathe(살아나는 빛들)",
    "sense": "콘서트 무대에서 퍼지고 사라지는 빛의 흐름에서 영감을 받아, 빛을 숨 쉬고 반응하는 하나의 생명체로 표현하고자 했다.",
    "description": "When Lights Breathe는 빛 자체가 살아나 생명체처럼 반응하는 인터랙티브 작품이다.\n콘서트에서 쏟아지는 빛처럼, 살아 숨쉬는 빛들이 관람자의 손길을 통해 하나씩 깨어나며 반딧불이로 깜빡이고, 나비로 날갯짓하고, 새 떼로 하늘을 가득 채운다. 관람자가 손을 뻗으면 빛이 깨어나고, 멀어지면 조용히 스며든다. 사용자의 터치가 이 세계의 숨결이 된다.",
    "link": "works/naylinaung-lights-breathe/index.html",
    "localLink": "works/naylinaung-lights-breathe/index.html",
    "displayMode": "local",
    "thumbnail": "thumbnails/s20251168.png",
    "inputDevice": "마우스 입력",
    "inputAction": "클릭·움직임",
    "output": "",
    "interactionGuide": "화면의 빛을 클릭해 변화를 시작해보세요.",
    "reaction": "관람자의 움직임에 따라 빛의 흐름과 생명체의 움직임이 변화합니다.마우스 움직임에 따라 빛이 모이고 퍼지며 생명체가 반응합니다.",
    "outputGuide": "",
    "sound": false,
    "rawInput": "#마우스이동 #마우스클릭",
    "rawOutput": "",
    "p5Original": "https://editor.p5js.org/naylinaunginu/full/gxKIbtr0T",
    "thumbnailOriginal": "https://drive.google.com/open?id=1OfPM7KuL_uegVyXd1ENUI_g0027C1WnO"
  },
  {
    "name": "최지수",
    "studentId": "20251191",
    "folder": "choi-jisu-emptying",
    "title": "생각비우기",
    "sense": "머리가 복잡해질 때 바깥에 나가 따뜻한 햇빛을 받으며 맑아지는 감각",
    "description": "생각이 많아질 때면 햇빛을 쐬며 생각을 비우곤 합니다. 이 작품 속 Creature는 머릿속에 존재하는 생각들입니다. 무겁게 존재하기도 가볍게 존재하기도 하며, 겹겹이 쌓이며 깊어지기도 합니다. 밤이 깊어지고 새벽이 될수록 생각은 점점 더 많아집니다. 마우스로 가까이 다가가면 점점 커지면서 생각이 깊어집니다. 하지만 낮이 되어 빛이 생기면 생각들은 하나둘씩 사라지고, 화면을 클릭해 빛을 더 많이 만들어내어 생각을 더 빠르게 없앨 수도 있습니다.",
    "link": "works/choi-jisu-emptying/index.html",
    "localLink": "works/choi-jisu-emptying/index.html",
    "displayMode": "local",
    "thumbnail": "thumbnails/s20251191.jpg",
    "inputDevice": "마우스 입력",
    "inputAction": "클릭·움직임",
    "output": "",
    "interactionGuide": "마우스를 생각 가까이 가져가보세요. · 화면을 클릭해보세요.",
    "reaction": "마우스로 가까이 다가가면 생각의 크기가 커집니다. / 마우스를 클릭하여 빛을 만들어내어 생각을 정리할 수 있습니다.",
    "outputGuide": "",
    "sound": false,
    "rawInput": "#마우스이동 #마우스클릭",
    "rawOutput": "",
    "p5Original": "https://editor.p5js.org/wlsuuo4/full/h60hpZre3",
    "thumbnailOriginal": "https://drive.google.com/open?id=1OEYyZZQ2YRHp6uKS19A5nr0haPA8naZd"
  },
  {
    "name": "최예원",
    "studentId": "20251189",
    "folder": "choi-yewon-rain",
    "title": "축축한 설렘",
    "sense": "비가 내리는 여름 오후, 친구들과 함께 버스를 타고 가던 그때의 감각",
    "description": "그 버스 안에서 느껴졌던 젖은 공기와 서늘한 바람 속, 축축하고 간질거리는 설렘의 감정을 담고 싶었습니다. 작품 속 Creature는 고요하지만 비를 내려주면 꿈틀거리며 기쁘게 반응하는 존재들로, 식물을 성장하게 만들기도 합니다. 빗방울을 맞지 못하면 움직임이 줄어들고, 말라버립니다.",
    "link": "https://editor.p5js.org/yewon1189/full/vGogxsuRU",
    "localLink": "works/choi-yewon-rain/index.html",
    "displayMode": "embed",
    "thumbnail": "thumbnails/s20251189.jpg",
    "inputDevice": "마우스 입력",
    "inputAction": "클릭",
    "output": "",
    "interactionGuide": "화면을 클릭해 빗방울을 떨어뜨려보세요.",
    "reaction": "빗방울의 파동을 맞은 존재들이 기쁘게 반응하게 됩니다",
    "outputGuide": "",
    "sound": false,
    "rawInput": "#마우스클릭",
    "rawOutput": "",
    "p5Original": "https://editor.p5js.org/yewon1189/full/vGogxsuRU",
    "thumbnailOriginal": "https://drive.google.com/open?id=1piDtNLiSgTS32px2jul8OjRu6JDRHtGK",
    "cropTop": 72
  },
  {
    "name": "이서현",
    "studentId": "20252835",
    "folder": "lee-seohyun-pending",
    "title": "달팽이관의 왈츠",
    "sense": "헤드폰을 끼고 음악을 감상할 때 귓속이 울리는 감각",
    "description": "헤드폰을 끼고 음악을 들을 때 느껴지는 고막의 울림과 귓속에서의 파동을 좋아합니다. 이 작품 속 파동(Creature)은 마우스로 클릭하면 터지고, 클릭하지 않으면 뭉쳐지며, 소리의 잔상을 남깁니다. 마우스를 좌우로 천천히 움직이면 낮과 밤의 음악 감상 차이를 이 Creature와 함께 느낄 수 있습니다.",
    "link": "works/lee-seohyun-pending/index.html",
    "localLink": "works/lee-seohyun-pending/index.html",
    "displayMode": "local",
    "thumbnail": "thumbnails/s20252835.jpg",
    "inputDevice": "마우스 입력",
    "inputAction": "클릭·움직임",
    "output": "사운드 출력",
    "interactionGuide": "화면을 한 번 클릭해 시작하고, 마우스를 좌우로 움직이며 중간중간 클릭해보세요.",
    "reaction": "마우스를 움직이거나 클릭함에 따라 파동의 형태가 달라지고, 환경이 달라집니다.",
    "outputGuide": "사운드 있음",
    "sound": true,
    "rawInput": "#마우스이동 #마우스클릭 #사운드",
    "rawOutput": "사운드 있음",
    "p5Original": "https://editor.p5js.org/iseohyeon105_2/full/mTYv8lKle",
    "thumbnailOriginal": "https://drive.google.com/open?id=1qaevFE4jokkqZHb2zAnnlbJdRXJHcPOO"
  },
  {
    "name": "지성혁",
    "studentId": "20253395",
    "folder": "ji-sunghyuk-jazz",
    "title": "문맹악단을 위한 재즈 모음곡 2번",
    "sense": "강약 조절이 완벽한 클래식 악곡을 들을 때 느껴지는 조화로운 벅차오름",
    "description": "쇼스타코비치의 왈츠 2번은 대중적으로도 널리 알려진 악곡이다. 균형 잡힌 박자감 위에서 희노애락이 느껴지는 선율의 수축과 팽창은 듣는 이를 감각의 바다로 몰입시킨다. 드넓은 공간감 속에서 관객은 고동하는 생명체와 스스로의 감각을 동일시하고, 생명체를 향해 손끝을 내밀게 된다. 설령 어떤 악기도 연주할 줄 모른다 해도, 생명체는 감각적인 손길에 친절히 반응하며 관객만의 왈츠를 시각화하는 것을 도와준다.",
    "link": "works/ji-sunghyuk-jazz/index.html",
    "localLink": "works/ji-sunghyuk-jazz/index.html",
    "displayMode": "local",
    "thumbnail": "thumbnails/s20253395.JPG",
    "inputDevice": "마우스·키보드 입력",
    "inputAction": "클릭·키조작",
    "output": "사운드 출력",
    "interactionGuide": "재생 버튼을 클릭한 뒤, 방향키와 숫자 키 1·2로 생물을 조작해보세요.",
    "reaction": "이동을 하며 키 조작에 따라 추가적인 요소들의 호응 (작은 크리쳐들 등장, 파동 생성)과 색 변형이 일어납니다.",
    "outputGuide": "사운드 있음",
    "sound": true,
    "rawInput": "#마우스클릭 #키보드 #사운드",
    "rawOutput": "사운드 있음",
    "p5Original": "https://editor.p5js.org/zeitgeist1111/full/9Ddm26LtB",
    "thumbnailOriginal": "https://drive.google.com/open?id=1sKoqePCEWAtxVJ6638ogHTg5PgbcLkkx"
  },
  {
    "name": "박예진",
    "studentId": "20251175",
    "folder": "park-yejin-festival",
    "title": "다붓다붓 페스티벌",
    "sense": "음악 페스티벌에서 노래에 맞춰 함께 달리고, 둥글게 모여 몸을 부딪혔던 감각",
    "description": "음악 축제에서 박자에 맞춰 뛰고, 둥글게 모인 공간의 중앙으로 몸을 부딪혔던 감각에서 출발했습니다. 작품 속 중앙의 Creature 무리는 설렘으로 가득 찬 채, 모이는 순간만을 기다립니다. 마우스를 중앙으로 움직여 그들이 모일 수 있게 도와주세요. 화면 위 연주하는 크리처들에게도 다가가 무대를 즐겨보세요. 사람을 무척 좋아하는, 활발한 존재들입니다.",
    "link": "works/park-yejin-festival/index.html",
    "localLink": "works/park-yejin-festival/index.html",
    "displayMode": "local",
    "thumbnail": "thumbnails/s20251175.jpg",
    "inputDevice": "마우스 입력",
    "inputAction": "클릭·움직임",
    "output": "사운드 출력",
    "interactionGuide": "화면을 클릭하고, 마우스를 중앙으로 움직여보세요.",
    "reaction": "중앙에 있던 크리쳐들이 모여들며 음악의 하이라이트 부분이 나오는 순간에 터지듯 퍼져나갑니다.",
    "outputGuide": "사운드 있음",
    "sound": true,
    "rawInput": "#마우스이동 #마우스클릭 #사운드",
    "rawOutput": "사운드 있음",
    "p5Original": "https://editor.p5js.org/yj3145/full/-SmADkYhD",
    "thumbnailOriginal": "https://drive.google.com/open?id=1VHyH1AuITZrFTQSPe7cDlGtdVTFLyKSz"
  },
  {
    "name": "허유민",
    "studentId": "20231939",
    "folder": "heo-yumin-hypnagogia",
    "title": "Hypnagogia",
    "sense": "잠에 들기 직전의 몽롱하고 불분명한 감각",
    "description": "이 작품은 잠에 들기 직전의 몽롱하고 불분명한 감각에서 출발했습니다. 화면 속 Creature는 잠을 좋아하고 느긋한 존재로, 의식과 무의식의 경계에서 천천히 잠에 빠져듭니다. 시간이 흐를수록 Creature의 세계는 입면기(Hypnagogia)의 환각처럼 패턴화된 이미지로 변하고, 현실의 형상은 점점 흐려집니다. 사용자는 마우스로 Creature를 클릭해 잠을 깨울 수 있지만, 깊이 잠들수록 여러 번 클릭해야 반응합니다. 잠들어가는 Creature의 의식과 무의식의 세계를 함께 느껴보세요.",
    "link": "https://editor.p5js.org/ymhuh/full/xn4sWoA3N",
    "localLink": "works/heo-yumin-hypnagogia/index.html",
    "displayMode": "embed",
    "thumbnail": "thumbnails/s20231939.jpg",
    "inputDevice": "마우스 입력",
    "inputAction": "클릭",
    "output": "",
    "interactionGuide": "화면을 마우스로 클릭해보세요.",
    "reaction": "마우스 클릭에 따라 잠에서 깨어납니다",
    "outputGuide": "",
    "sound": false,
    "rawInput": "#마우스클릭",
    "rawOutput": "",
    "p5Original": "https://editor.p5js.org/ymhuh/full/xn4sWoA3N",
    "thumbnailOriginal": "https://drive.google.com/open?id=1kF8QFgm3aPrIpaqR5bEGiArTBzEtlTfJ",
    "cropTop": 72
  },
  {
    "name": "손혜원",
    "studentId": "20251179",
    "folder": "son-hyewon-glass",
    "title": "유리컵 속 생명체",
    "sense": "물과 투명체를 통한 빛의 시각적 자극, 그리고 찰랑거리고 말랑거리는 감각",
    "description": "투명한 유리 비커 속에 갇혀 유영하는 생명체는 외부의 자극에 반응하며 자신의 존재를 드러낸다. 사용자의 손길이 닿을 때마다 생명체는 본연의 고요한 흰색에서 열정적인 분홍색으로 물들며, 그 순간 터져 나오는 몽글몽글한 입자들은 내면의 감정이 밖으로 투영되는 찰나를 시각화한다. 유리라는 폐쇄적 공간과 자유로운 움직임의 대비를 통해, 정적인 환경 속에서도 생명력이 어떻게 발현되고 확장되는지를 감각적으로 탐구하는 인터랙티브 작품이다.",
    "link": "https://editor.p5js.org/ne.341358/full/Qtyoy1JyP",
    "localLink": "works/son-hyewon-glass/index.html",
    "displayMode": "embed",
    "canvasWidth": 1200,
    "canvasHeight": 600,
    "cropTop": 72,
    "thumbnail": "thumbnails/s20251179.jpg",
    "inputDevice": "마우스 입력",
    "inputAction": "클릭·움직임",
    "output": "",
    "interactionGuide": "마우스를 움직이고, 화면을 클릭해보세요.",
    "reaction": "마우스와 생명체의 거리, 클릭 횟수에 따라 생명체의 반응이 달라집니다.",
    "outputGuide": "",
    "sound": false,
    "rawInput": "#마우스이동 #마우스클릭",
    "rawOutput": "",
    "p5Original": "https://editor.p5js.org/ne.341358/full/Qtyoy1JyP",
    "thumbnailOriginal": "https://drive.google.com/open?id=1JOW-yuq1EAbXVNp2pS5kzhlhOSYeRsYS"
  },
  {
    "name": "배금비",
    "studentId": "20251177",
    "folder": "bae-geumbi-pending",
    "title": "피버타임",
    "sense": "노래를 들으며 떠오르는 내 안의 각기 다른 자아와 고민들을 마주하는 순간",
    "description": "노래를 들을 때 가장 많은 생각을 한다는 사실에서 출발했다. 내 안의 다양한 자아와 고민들을 풀어내고 싶었고, 전체적인 비주얼은 전자음악과 디제잉에서 영감을 받아 구현했다. 사용자는 각기 다른 환경에 들어가 저마다 다른 성격의 크리처들을 느끼고 교감할 수 있다. 자신만의 여러 자아를 존중하고 인정하며, 친하게 지내길 바란다.",
    "link": "works/bae-geumbi-pending/index.html",
    "localLink": "works/bae-geumbi-pending/index.html",
    "displayMode": "local",
    "thumbnail": "thumbnails/s20251177.png",
    "inputDevice": "터치센서 입력",
    "inputAction": "터치",
    "output": "사운드 출력",
    "interactionGuide": "앞에 놓인 터치 패드를 손으로 터치해보세요.",
    "reaction": "터치 입력에 반응하여 각 사운드에 맞춰 움직이기 시작함",
    "outputGuide": "사운드 있음",
    "sound": true,
    "rawInput": "#터치센서 #사운드",
    "rawOutput": "사운드 있음",
    "p5Original": "https://editor.p5js.org/rainy22/full/ou4ELJd-8",
    "thumbnailOriginal": "https://drive.google.com/open?id=1Jrhe1_l5mV8planIaiaJnMwboMXe1Wxn"
  },
  {
    "name": "신자운",
    "studentId": "20253197",
    "folder": "shin-jawoon-pending",
    "title": "잊혀지는 것들의 바다",
    "sense": "오래되고 버려진 물건들도 저마다의 이야기를 간직하고 있을 것이라는 생각",
    "description": "오래되고 버려지는 물건들을 보면, 이 물건에는 얼마나 많은 이야기가 담겨 있을까 생각하게 됩니다. 그런 물건들이 소멸되기 전에 이야기의 조각들을 수집하는 존재가 있다면 어떨까 하는 상상에서 시작되었습니다. 이 Creature는 호기심 많은 존재로, 마우스를 클릭한 채 움직이면 발광하며 따라오고, 물건과 접촉하면 자신의 빛을 나눠주어 그 이야기를 밝혀냅니다.",
    "link": "works/shin-jawoon-pending/index.html",
    "localLink": "works/shin-jawoon-pending/index.html",
    "displayMode": "local",
    "thumbnail": "thumbnails/s20253197.jpg",
    "inputDevice": "마우스 입력",
    "inputAction": "드래그",
    "output": "사운드 출력",
    "interactionGuide": "마우스를 클릭한 채로 화면 위를 움직여보세요.",
    "reaction": "크리쳐가 마우스를 따라오고, 크리쳐가 오브젝트에 머물면 오브젝트의 이야기가 드러납니다.",
    "outputGuide": "사운드 있음",
    "sound": true,
    "rawInput": "#마우스드래그 #사운드",
    "rawOutput": "사운드 있음",
    "p5Original": "https://editor.p5js.org/shinjaw55/full/XSq31YMr4",
    "thumbnailOriginal": "https://drive.google.com/open?id=1hK03o9ZhlXP7ammrL6VUwTGQ5VuTRaeJ"
  },
  {
    "name": "박서진(24)",
    "studentId": "20241660",
    "folder": "park-seojin-pending",
    "title": "공원의 악보",
    "sense": "햇빛이 기울기 시작한 오후 4시, 잔디밭의 모든 소리가 한꺼번에 어우러져 하나의 하모니가 되던 순간",
    "description": "햇빛이 기울기 시작한 오후 4시, 잔디밭의 소리. 이 작품 속 Creature들은 바람, 새, 아이들, 자전거, 풀벌레처럼 공원을 함께 채우는 존재들입니다. 마우스를 각 선에 가져다 대면 그 Creature의 소리가 선명해지고 나머지는 배경으로 물러납니다. 모든 선이 동시에 울릴 때, 비로소 공원의 하모니가 완성됩니다.",
    "link": "works/park-seojin-pending/index.html",
    "localLink": "works/park-seojin-pending/index.html",
    "displayMode": "local",
    "thumbnail": "thumbnails/s20241660.png",
    "inputDevice": "마우스 입력",
    "inputAction": "움직임",
    "output": "사운드 출력",
    "interactionGuide": "마우스를 화면 위에서 천천히 움직여보세요.",
    "reaction": "마우스를 각각의 Creature 위로 가져다대면 해당 Creature의 소리가 선명하게 들리고 나머지는 배경으로 물러납니다",
    "outputGuide": "사운드 있음",
    "sound": true,
    "rawInput": "#마우스이동 #사운드",
    "rawOutput": "사운드 있음",
    "p5Original": "https://editor.p5js.org/restresp1/full/ofIIt56E_",
    "thumbnailOriginal": "https://drive.google.com/open?id=17GUsyyTZjOTkCx0kA4ye_xKLpDWKz4LD"
  },
  {
    "name": "김태리",
    "studentId": "20251167",
    "folder": "kim-taeri-blanket",
    "title": "이불 속은 위험해",
    "sense": "보들보들하고 포근한 이불 속",
    "description": "다들 보들보들하고 포근한 이불 속에서 빠져나오지 못했던 경험이 있죠. 이 크리처는 자신을 만지는 관람자를 반갑게 맞이하는 존재로, 처음에는 가까이 다가오다 어느 순간 조용히 곁을 에워쌉니다. 마우스로 크리처의 온기를 느끼다 보면 어느새 그 포근함 속에 감싸이고, 나른한 졸음이 밀려옵니다. 키보드를 통해 잠깐 벗어나 볼 수도 있지만, 과연 빠져나올 수 있을지는 모릅니다.",
    "link": "works/kim-taeri-blanket/index.html",
    "localLink": "works/kim-taeri-blanket/index.html",
    "displayMode": "local",
    "thumbnail": "thumbnails/s20251167.jpg",
    "inputDevice": "마우스·키보드 입력",
    "inputAction": "움직임·키조작",
    "output": "",
    "interactionGuide": "마우스를 움직여보세요. · 잠시 멈추고 기다려보세요. · 키보드를 눌러 잠에서 깨어나보세요.",
    "reaction": "마우스의 움직임에 따라 Creature의 거대한 몸이 살짝 들어올려지며, 따뜻한 색으로 변화합니다. - Creature가 마우스를 감싸 안아줍니다 - 키보드 화살표 양옆 키를 연타하여 벗어날 수 있습니다",
    "outputGuide": "",
    "sound": false,
    "rawInput": "#마우스이동 #키보드",
    "rawOutput": "",
    "p5Original": "https://editor.p5js.org/tellme95/full/PFO0bzr6T",
    "thumbnailOriginal": "https://drive.google.com/open?id=1sl4zoiPqqt6zrQmOnefLwWI_s4g088OC"
  }
];
